name: "Open PR to main branch"

on:
  workflow_call:

jobs:
  test_build:
    runs-on: self-hosted
    name: Test code and build image 
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Python 3.9.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.10'

      - name: Create Virtual Environment
        shell: bash
        run: |-
          echo "HOME=/root" >> $GITHUB_ENV
          python3.9 -m venv .local;

      - name: Install Dependencies
        shell: bash
        run: |-
          source .local/bin/activate;
          pip3.9 install --upgrade pip;
          pip3.9 install keyrings.google-artifactregistry-auth;
          pip3.9 install -U . --extra-index-url https://europe-west1-python.pkg.dev/common-main-cfc4/ai-packages/simple/;
          echo test;
          
      - name: Build the Docker image
        shell: bash
        run: |-
          docker build --build-arg working_dir=$PWD .;