name: Deploy branch to dev

on:
  workflow_call:
    inputs:
        image_repo:
          required: true
          type: string
          default: europe-docker.pkg.dev/common-main-cfc4/eu.gcr.io
          description: "Your container registry repository - like europe-docker.pkg.dev/common-main-cfc4/eu.gcr.io"
        app_squad:
          required: true
          type: string
          description: "Your app Squad - where your app is located inside argoCD (backend, ai, qa...)"
        github_email:
          required: true
          type: string
          description: "Automatic CI/CD commits will be done by this email"
        github_user:
          required: true
          type: string
          description: "Automatic CI/CD commits will be done by this user"
        k8s_manifests_repo:
          required: true
          type: string
          description: "Owner and repo name containing your k8s manifests - like ultimateai/k8s-manifests"
        branch_name:
          required: true
          type: string
          description: "Which branch you want to build and deploy to dev"
        test_command:
          required: false
          type: string
          description: "Command for running your tests, defaults to - npm run test"
          default: "npm run test"
        build_command:
          required: false
          type: string
          description: "Command for building your app, defaults to - npm run build"
          default: "npm run build"
        lint_command:
          required: false
          type: string
          description: "Command for linting your app, defaults to - npm run lint"
          default: "npm run lint"
        npm_install_command:
          required: false
          type: string
          description: "Command for npm i, defaults to - npm i"
          default: "npm i"
        node_version:
          required: false
          type: string
          default: "16.x"
          description: "Node version used in the pipeline, defaults to 16.x"
        npm_version:
          required: false
          type: string
          description: "Npm version used in the pipeline, defaults to LTS version"


env:
  IMAGE_REPO: ${{ inputs.image_repo }}
  APP_SQUAD: ${{ inputs.app_squad }}
  GITHUB_EMAIL: ${{ inputs.github_email }}
  GITHUB_USER: ${{ inputs.github_user }}
  K8S_MANIFESTS_REPO: ${{ inputs.k8s_manifests_repo }}
  BRANCH_NAME: ${{ inputs.branch_name }}
  TEST_COMMAND: ${{ inputs.test_command }}
  BUILD_COMMAND: ${{ inputs.build_command }}
  LINT_COMMAND: ${{ inputs.lint_command }}
  NPM_INSTALL_COMMAND: ${{ inputs.npm_install_command }}
  NODE_VERSION: ${{ inputs.node_version }}
  NPM_VERSION: ${{ inputs.npm_version }}
  GCR_ENABLED: ${{ vars.GCR_ENABLED || 'true' }}
  GAR_ENABLED: ${{ vars.GAR_ENABLED || 'true' }}


jobs:
  deploy:
    name: Update k8s manifest repo for development deployment
    runs-on: preemptible-runners
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Validation
        if: ${{ env.GCR_ENABLED != 'true' && env.GAR_ENABLED != 'true' }}
        run: |
          echo "At least one of GCR_ENABLED or GAR_ENABLED must be set to true.'
          exit 1

      - name: Checkout to selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        if: ${{ env.NPM_VERSION }}
        run: npm i -g npm@${{ env.NPM_VERSION }} --registry=https://registry.npmjs.org

      - id: "image_name"
        name: "Extract repo name and update IMAGE_NAME"
        run: |-
          REPO_DOMAIN=$(echo $IMAGE_REPO | cut -d '/' -f 1)
          case $REPO_DOMAIN in
            *gcr.io)
              GCR_DOMAIN=$REPO_DOMAIN
              GAR_DOMAIN=europe-docker.pkg.dev
              GCR_IMAGE_REPO=$IMAGE_REPO
              GAR_IMAGE_REPO=europe-docker.pkg.dev/common-main-cfc4/eu.gcr.io ;;
            *pkg.dev)
              GCR_DOMAIN=eu.gcr.io
              GAR_DOMAIN=$REPO_DOMAIN
              GCR_IMAGE_REPO=eu.gcr.io/ultimateai-169214
              GAR_IMAGE_REPO=$IMAGE_REPO ;;
          esac

          GCR_IMAGE_NAME=$GCR_IMAGE_REPO"/"${{ github.event.repository.name }}
          GAR_IMAGE_NAME=$GAR_IMAGE_REPO"/"${{ github.event.repository.name }}

          echo "gcr_domain=$GCR_DOMAIN" >> $GITHUB_OUTPUT
          echo "gar_domain=$GAR_DOMAIN" >> $GITHUB_OUTPUT
          echo "gcr_image_repo=$GCR_IMAGE_REPO" >> $GITHUB_OUTPUT
          echo "gar_image_repo=$GAR_IMAGE_REPO" >> $GITHUB_OUTPUT
          echo "gcr_image_name=$GCR_IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "gar_image_name=$GAR_IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Get .env file and scheduler
        run: |-
          cat "deployment_envs/dev.env" > $HOME/dev-copy.env
          cat "deployment_schedules/dev" > $HOME/dev-scheduler-copy

      - id: get_image_tag
        name: Get image tag from branch name and commitId
        run: |-
          FIXED_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr / -)
          TAG=$FIXED_BRANCH_NAME-$(git rev-parse --short HEAD)
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Export Home
        run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3.2.2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

       ### Authentings with Google Cloud to Push Image to GCR ###
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER_NAME }}"
          service_account: ${{ secrets.GSA_GCR_EMAIL }}

      - name: Install npm Packages
        run: |
          if grep -q artifactregistry-login "package.json"; then
            npm run artifactregistry-login -- --credential-config .npmrc
          fi
          $NPM_INSTALL_COMMAND

      - name: Lint
        if: ${{ env.LINT_COMMAND }}
        run: $LINT_COMMAND

      - name: Test
        if: ${{ env.TEST_COMMAND }}
        run: $TEST_COMMAND

      - name: build
        if: ${{ env.BUILD_COMMAND }}
        run: $BUILD_COMMAND

      - name: "Authenticating docker to push to gcr"
        if: ${{ env.GCR_ENABLED == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: "${{ steps.image_name.outputs.GCR_DOMAIN }}"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: "Authenticating docker to push to gar"
        if: ${{ env.GAR_ENABLED == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: "${{ steps.image_name.outputs.GAR_DOMAIN }}"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Docker build
        run: |-
          docker build -t "${GCR_IMAGE_NAME}:${TAGS}" -t "${GAR_IMAGE_NAME}:${TAGS}" .
        shell: bash
        env:
          TAGS: ${{ steps.get_image_tag.outputs.image_tag }}
          GCR_IMAGE_NAME: ${{ steps.image_name.outputs.gcr_image_name }}
          GAR_IMAGE_NAME: ${{ steps.image_name.outputs.gar_image_name }}

      - name: Docker push to GCR
        if: ${{ env.GCR_ENABLED == 'true' }}
        run: |-
          docker push "${IMAGE_NAME}:${TAGS}"
        shell: bash
        env:
          TAGS: ${{ steps.get_image_tag.outputs.image_tag }}
          IMAGE_NAME: ${{ steps.image_name.outputs.gcr_image_name }}

      - name: Docker push to GAR
        if: ${{ env.GAR_ENABLED == 'true' }}
        run: |-
          docker push "${IMAGE_NAME}:${TAGS}"
        shell: bash
        env:
          TAGS: ${{ steps.get_image_tag.outputs.image_tag }}
          IMAGE_NAME: ${{ steps.image_name.outputs.gar_image_name }}

      ##Deploy to dev
      - name: "Checkout k8s manifests"
        uses: actions/checkout@v3
        with:
          repository: ${{ env.K8S_MANIFESTS_REPO }}
          token: ${{ secrets.ULTIMATE_GITHUB_PAT }}

      - name: Update the Image tags for Dev Environment
        run: |-
            cd $APP_SQUAD/${{ github.event.repository.name }}/overlay/${K8S_ENV_NAME}
            cat $HOME/dev-copy.env > dev.env
            scheduler=$(cat $HOME/dev-scheduler-copy)
            yq ".spec.schedule = \"$scheduler\"" -i cronjob.yaml
            kustomize edit set image app=${IMAGE_NAME}:${TAG}
            cat kustomization.yaml
            git config --local user.email $GITHUB_EMAIL
            git config --local user.name $GITHUB_USER
            git commit -m "update image to ${IMAGE_NAME}:${TAG}" -a
            git push ${REMOTE_REPO} HEAD:main --force
        env:
          TAG: ${{ steps.get_image_tag.outputs.image_tag }}
          REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
          K8S_ENV_NAME: development
          IMAGE_NAME: ${{ steps.image_name.outputs.gar_image_name }}
