name: "Lint PR title"

on:
  workflow_call:

jobs:
  main:
    name: Validate PR title
    runs-on: self-hosted
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            breaking
            minor
            major
            patch
          requireScope: false
          subjectPattern: https:\/\/(www\.)?ultimateai\.atlassian\.net\/browse\/([-a-zA-Z0-9 /-]+)
          # If `subjectPattern` is configured, you can use this property to override
          # the default error message that is shown when the pattern doesn't match.
          # The variables `subject` and `title` can be used within the message.
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please start with the jira issue which originated your work - like feat(scope): https://ultimateai.atlassian.net/browse/PLT-000