name: Manual deploy

on:
  workflow_call:
    inputs:
        image_repo:
          required: true
          type: string
          description: "Your container registry repository - like eu.gcr.io/ultimateai-169214"
        app_squad:
          required: true
          type: string
          description: "Your app Squad - where your app is located inside argoCD (backend, ai, qa...)"
        environment:
          required: true
          type: string
          description: "In which environment do you want to deploy"
        version:
          required: false
          type: string
          description: "Which tag do you want to deploy - if none, latest release will be used"
        github_email:
          required: true
          type: string
          description: "Automatic CI/CD commits will be done by this email"
        github_user:
          required: true
          type: string
          description: "Automatic CI/CD commits will be done by this user"
        k8s_manifests_repo:
          required: true
          type: string
          description: "Owner and repo name containing your k8s manifests - like ultimateai/k8s-manifests"
        allowed_users:
          required: false
          type: string
          description: "Users allowed to deploy specific versions - format should be like user1,user2,user3"


env:
  IMAGE_REPO: ${{ inputs.image_repo }}
  APP_SQUAD: ${{ inputs.app_squad }}
  ENVIRONMENT: ${{ inputs.environment }}
  VERSION: ${{ inputs.version }}
  GITHUB_EMAIL: ${{ inputs.github_email }}
  GITHUB_USER: ${{ inputs.github_user }}
  K8S_MANIFESTS_REPO: ${{ inputs.k8s_manifests_repo }}
  ALLOWED_USERS: ${{ inputs.allowed_users }}


jobs:
  deploy:
    name: Update k8s-manifest repo
    runs-on: self-hosted
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          

      - id: "image_name"
        name: "Get repo name and update IMAGE_NAME"
        run: |- 
          IMAGE_NAME=$IMAGE_REPO"/"${{ github.event.repository.name }}
          echo $IMAGE_NAME
          echo '::set-output name=image_name::'$IMAGE_NAME

      - id: fetch_latest_release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.ULTIMATE_GITHUB_PAT }}

      - id: tag_to_deploy
        name: Calculate version to deploy
        run: |-
          if [[ -z "${VERSION}"  ]]; then
            TAG=${{ steps.fetch_latest_release.outputs.tag_name }}
          else
            if [[ -z "${ALLOWED_USERS}"  ]]; then
              echo "You have selected a specific version to deploy, but provided no list of people who can deploy specific versions (allowed_users)"
              exit 1
            fi
            IFS=',' read -r -a array <<< "$ALLOWED_USERS"
            if [[ " ${array[*]} " =~ ${{ github.actor }} ]]; then
              echo "This user - ${{ github.actor }} - is allowed"
              TAG=$VERSION
            else
              echo "Sorry,${{ github.actor }}, you are not allowed to choose specific version to deploy - contact your platform team"
              exit 1
            fi
          fi
          echo '::set-output name=tag::'$TAG

      ##Automatic deploy to development on merged PR to main

      - name: "Checkout k8s manifests"
        uses: actions/checkout@v3
        with:
          repository: ${{ env.K8S_MANIFESTS_REPO }}
          token: ${{ secrets.ULTIMATE_GITHUB_PAT }}
      
      - name: Check if version is already deployed in stage, if trying to deploy in prod
        run: |-
          if [[ "${ENVIRONMENT}" = "production" ]]; then
            STAGE_VERSION=$(cat $APP_SQUAD/${{ github.event.repository.name }}/overlay/staging/kustomization.yaml | yq .images.0.newTag)
            if [[ ! "${STAGE_VERSION}" = "${TAGS}" ]]; then
              echo "Stage version is $STAGE_VERSION and you want to deploy to production $TAGS. Please, deploy to staging env first"
              exit 1
            fi
          fi
        env:
          TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
          
      - name: Update the Image tags for Dev Environment for CronJob k6-loadtest
        run: |-
          cd $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT
          kustomize edit set image app=${IMAGE_NAME}:${TAGS}
          cat kustomization.yaml
          git config --local user.email $GITHUB_EMAIL
          git config --local user.name $GITHUB_USER
          git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a
          git push ${REMOTE_REPO} HEAD:main --force 
        env:
          TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
          REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}

      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\Deployed ${{IMAGE_NAME}}:${{TAGS}} in ${{ENVIRONMENT}} by ${{ github.actor }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
      