name: Merged PR to main branch

on:
  workflow_call:
    inputs:
        image_repo:
          required: true
          type: string
          description: "Your container registry repository - like eu.gcr.io/ultimateai-169214"
        app_squad:
          required: true
          type: string
          description: "Your app Squad - where your app is located inside argoCD (backend, ai, qa...)"
        github_email:
          required: true
          type: string
          description: "Automatic CI/CD commits will be done by this email"
        github_user:
          required: true
          type: string
          description: "Automatic CI/CD commits will be done by this user"
        k8s_manifests_repo:
          required: true
          type: string
          description: "Owner and repo name containing your k8s manifests - like ultimateai/k8s-manifests"
        update_file:
          required: false
          type: string
          description: "The file with the version you want to update"
        changelog:
          required: false
          type: boolean
          description: "Update changelog"
        initial_release:
          required: false
          type: string
          description: "In case no release is present in the repo, which one should be the base release from which to bump - defaults to 0.0.0"
          default: "0.0.1"
        automatic_deployment_to:
          required: false
          type: string
          description: "To which env you want to automatically deploy"
          default: "development"
        
        

env:
  IMAGE_REPO: ${{ inputs.image_repo }}
  APP_SQUAD: ${{ inputs.app_squad }}
  GITHUB_EMAIL: ${{ inputs.github_email }}
  GITHUB_USER: ${{ inputs.github_user }}
  K8S_MANIFESTS_REPO: ${{ inputs.k8s_manifests_repo }}
  UPDATE_FILE: ${{ inputs.update_file }}
  CHANGELOG: ${{ inputs.changelog }}
  INITIAL_RELEASE: ${{ inputs.initial_release }}
  AUTOMATIC_DEPLOYMENT_TO: ${{ inputs.automatic_deployment_to }}
  

jobs:
  bump-release:
    name: Bump release
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version and release
        uses: ultimateai/bump-action@v0.5.4
        with:
          github_token: ${{ secrets.ULTIMATE_GITHUB_PAT }}
          infer_bump_from_commit: true
          update_file: ${{ env.UPDATE_FILE }}
          changelog: ${{ env.CHANGELOG }}
          initial_release: ${{ env.INITIAL_RELEASE }}

  push-and-deploy:
    name: Push image with updated tag and update development environment
    runs-on: self-hosted
    needs: bump-release
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get environment.env file for updating k8s-manifest repo
        run: |-
          if [[ "${AUTOMATIC_DEPLOYMENT_TO}" = "staging" ]]; then
            cat "deployment_envs/stage.env" > $HOME/envfile.env
          else
            cat "deployment_envs/dev.env" > $HOME/envfile.env
          fi
          if [[ -f "common.env" ]]; then
            cat "deployment_envs/common.env" > $HOME/commonfile.env
          fi

      - id: "image_name"
        name: "Get repo name and update IMAGE_NAME"
        run: |- 
          IMAGE_NAME=$IMAGE_REPO"/"${{ github.event.repository.name }}
          echo $IMAGE_NAME
          echo '::set-output name=image_name::'$IMAGE_NAME

      - id: fetch_latest_release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.ULTIMATE_GITHUB_PAT }}

      - name: Export Home
        run: echo "HOME=/root" >> $GITHUB_ENV

      ##  Needs to be added so as to pull common Libs from bitbucket ##
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BB_SSH_KEY }}
          name: id_rsa
          known_hosts: bitbucket.org
          if_key_exists: ignore

      ### Authentings with Google Cloud to Push Image to GCR ###
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER_NAME }}"
          service_account: ${{ secrets.GSA_GCR_EMAIL }}

      - name: "Authenticating docker to push to gcr"
        uses: "docker/login-action@v1"
        with:
          registry: "eu.gcr.io"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Install npm Packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: build
        run: npm run build
      
      - name: Docker build
        run: |-
          echo "$SSH_KEY" > id_rsa
          docker build -t "${IMAGE_NAME}:${TAGS}" .
        shell: bash
        env:
          SSH_KEY: ${{ secrets.BB_SSH_KEY }}
          TAGS: ${{ steps.fetch_latest_release.outputs.tag_name }}
          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}

      - name: Docker push
        run: |-
          docker push "${IMAGE_NAME}:${TAGS}"
        shell: bash
        env:
          TAGS: ${{ steps.fetch_latest_release.outputs.tag_name }}
          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}

      ##Automatic deploy to development on merged PR to main
      - name: "Checkout k8s manifests"
        uses: actions/checkout@v3
        with:
          repository: ${{ env.K8S_MANIFESTS_REPO }}
          token: ${{ secrets.ULTIMATE_GITHUB_PAT }}
          
      - name: Update the Image tags for Dev Environment
        run: |-
          if [[ "${K8S_ENV_NAME}" == "development" || "${K8S_ENV_NAME}" == "staging"  ]]; then
            if [[ -f "$HOME/commonfile.env" ]]; then
              cat $HOME/commonfile.env > $APP_SQUAD/${{ github.event.repository.name }}/base/base.env
            fi          
            cd $APP_SQUAD/${{ github.event.repository.name }}/overlay/${K8S_ENV_NAME}
            FILE_ENV=$(ls | grep ".env");cat $HOME/envfile.env > $FILE_ENV
            kustomize edit set image app=${IMAGE_NAME}:${TAGS}
            cat kustomization.yaml
            git config --local user.email $GITHUB_EMAIL
            git config --local user.name $GITHUB_USER
            git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a
            git push ${REMOTE_REPO} HEAD:main --force 
          else
            echo "You want to deploy automatically to ${K8S_ENV_NAME}, which is not development nor staging. This is not allowed."
            exit 1
          fi
        env:
          TAGS: ${{ steps.fetch_latest_release.outputs.tag_name }}
          REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
          K8S_ENV_NAME: ${{ env.AUTOMATIC_DEPLOYMENT_TO }}
          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
      
